env:
  browser: true
  es6: true
extends:
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "import"
settings:
  import/resolver:
    node: { "extensions": [".js", ".jsx", ".ts", ".tsx"] }
  import/parsers:
    typescript-eslint/parser: [.ts, .tsx]
rules:
  comma-dangle: ["error", "always-multiline"]
  indent: ["error", 4]
  quotes: ["error", "double"]
  semi: ["error", "never"]
  no-new: 0
  import/order: ["error", {
    groups : [
      "builtin",
      "external",
      ["sibling", "parent"],
      "index"
    ],
    newlines-between: "always",
    alphabetize: {
      order: "asc",
      caseInsensitive: true
    }
  }]
  import/extensions: ["error", never]
