#!/usr/bin/env bash
set -ex

plot_title="Hello Code Ocean"
number_of_cycles=3
input_data="../data/sample-data.txt"

matlab -nodisplay -nosoftwareopengl -r \
  "main('$plot_title', $number_of_cycles, '$input_data')"
