Version:
  Version: "{{config.version.version}}"
  Label: "{{config.version.label}}"
General:
  APIBasePath: /api
  PublicAPIURL: https://codeocean.com/api
  BaseURL: https://{{config.domains.app}}
  FilesURITemplate: https://{{config.domains.files}}/files/{owner_id}/{capsule_id}{+path}
  DatasetsURITemplate: https://{{config.domains.files}}/datasets/{owner_id}/{dataset_id}{+path}
  InputURITemplate: https://{{config.domains.files}}/input/{owner_id}/{capsule_id}{+path}
  AssetsBaseURL: https://{{config.domains.app}}/a
  GiteaProxyBaseURL: https://{{config.domains.git}}
  NetworkType: compose
NewUser:
  EulaVersion: 1
Security:
  TrustForwardedHeaders: true
  TrustedGitHosts:
    - github.com
    - gitlab.com
    - bitbucket.org
  TokenExpiration: 24h
  FileTokenExpiration: 1h
  FileTokenCookieDomain: {{config.domains.files}}
  SecureTokens: true
  UseCors: false
  {{#if secrets.auth.builtin.reCaptchaApiKey}}
  ReCaptchaAPIKey: {{secrets.auth.builtin.reCaptchaApiKey}}
  {{/if}}
  {{#if secrets.auth.systemAPIKey}}
  SystemAPIKey: {{secrets.auth.systemAPIKey}}
  {{/if}}
Auth:
  DisableBuiltinSignup: true
  DisableAnonymousUsers: true
  PrivateKeyPath: /app/keys/app.rsa
  PublicKeyPath: /app/keys/app.rsa.pub
  SAML:
    PrivateKeyPath: /app/keys/app.key
    PublicKeyPath: /app/keys/app.cert
    {{#if config.auth.saml}}
    {{#with config.auth.saml}}
    IdentityProviders:
      - Domain: {{domain}}
        {{#if metadataUrl}}
        MetadataURL: {{metadataUrl}}
        {{/if}}
        {{#if metadata}}
        {{#with metadata}}
        Metadata:
          EntityID: {{entityID}}
          SSOURL: {{ssoUrl}}
          {{#*inline "Certificate"}}
{{certificate}}
          {{/inline}}
          Certificate: |
            {{> Certificate}}
        {{/with}}
        {{/if}}
    {{/with}}
    {{/if}}
  OAuth2:
    {{#if config.auth.allowedDomains}}
    AllowedDomains:
      {{#each config.auth.allowedDomains}}
      - {{this}}
      {{/each}}
    {{~/if}}
    {{#if config.auth.google.clientID}}
    Google:
      ClientID: {{config.auth.google.clientID}}
      ClientSecret: {{secrets.auth.google.clientSecret}}
    {{/if}}
AWS:
  AccountID: {{config.aws.accountId}}
  Region: {{config.aws.region}}
  S3:
    BaseURL: https://{{config.domains.app}}/s3
    Buckets:
      Datasets: {{buckets.datasets}}
      InputFiles: {{buckets.inputfiles}}
      Public: {{buckets.public}}
      Results: {{buckets.results}}
      Temp: {{buckets.temp}}
  EC2:
    DedicatedMachineLaunchTemplate: {{dedicatedMachineLaunchTemplateID}}
    DedicatedMachineLaunchTemplateVersion: {{dedicatedMachineLaunchTemplateVersion}}
DiskStorage:
  WorkspacesPath: /data/workspaces
  {{#if config.features.capsuleCache}}
  CapsuleCachePath: /capsule-cache
  {{/if}}
  DatasetsPath: /data/datasets
  WorkerPath: /data/worker
  RationalDataPath: /data
  Overlay:
    RepoDir: repo
    OverlayDir: overlay
    WorkDir: work
    Fallback: false
CloudWorkstation:
  IdleTimeout: 120  # 2 hrs
CouchDB:
  URL: http://couchdb:5984
  Username: admin
  Password: {{secrets.couchdb.adminPassword}}
Docker:
  RegistryHost: {{config.services.registryHost}}
  DeployForTesting: false
  DeleteDeployedImages: false
Gitea:
  URL: http://gitea:3030
  AdminUser: gitea
  AdminPassword: {{secrets.gitea.adminPassword}}
  CommonPassword: {{secrets.gitea.commonPassword}}
  VerificationUser: co-verification
  VerifiedUser: verified
  AuxPassword: {{secrets.gitea.auxPassword}}
  ReadOnlyUser: readonly
  ReadOnlyPassword: {{secrets.gitea.readonlyPassword}}
GitProviders:
  {{#if config.gitProviders.github.org}}
  - Name: GitHub
    Domain: github.com
    Organization: {{config.gitProviders.github.org}}
  {{/if}}
Redis:
  {{#if config.services.aws.redis.enabled}}
  Address: {{services.redis.address}}:6379
  TLS: true
  {{else}}
  Address: redis:6379
  {{/if}}
  Password: "{{secrets.redis.password}}"
Elasticsearch:
  {{#if config.services.aws.elasticsearch.enabled}}
  URL: https://{{services.elasticsearch.address}}
  AWSV4Signing: true
  DisableSniffing: true
  {{else}}
  URL: http://es:9200
  {{/if}}
AnalyticsDB:
  Host: {{services.analyticsdb.host}}
  Port: {{services.analyticsdb.port}}
  User: {{services.analyticsdb.username}}
  Password: {{secrets.analyticsdb.password}}
  SSL: true
  DBName: codeocean
  ObjectsTableName: objects
  EventsTableName: events
WDT:
  DockerImage: 524950183868.dkr.ecr.us-east-1.amazonaws.com/codeocean/wdt:2019-02-14-b8f978f
  TempDir: wdt_temp
  Network: {{#if config.deployment.singleInstance}}codeocean_default{{else}}host{{/if}}
  PortRangeBegin: 20000
  PortRangeEnd: 30000
Tools:
  DockerImage: 524950183868.dkr.ecr.us-east-1.amazonaws.com/codeocean/tools:2021-04-13-7370b9c
Segment:
  {{#if secrets.segment.backendApiKey}}
  APIKey: {{secrets.segment.backendApiKey}}
  {{/if}}
  {{#if secrets.segment.frontendApiKey}}
  APIKeyFE: {{secrets.segment.frontendApiKey}}
  {{/if}}
  StatInterval: 3600
InitData:
  Affiliations: false
  Fields: true
  Licenses: false
  Journals: false
  Languages:
    Matlab: true
    Octave: true
    R: true
    Julia: true
    Python: true
    C: true
    Fortran: true
    Java: true
    Perl: true
    Lua: true
    Stata: true
    Wolfram: true
    Other: true
Resources:
  MachineTypes:
    0:
      Slot:
        CPU: {{slotsConfig.general.slot.cpu}}
        Memory: {{slotsConfig.general.slot.memory}}
      DefaultClass: {{slotsConfig.general.defaultClass}}
      Classes:
        {{#each slotsConfig.general.classes}}
        {{this.id}}:
          Name: {{this.name}}
          Description: {{this.description}}
          Order: {{this.order}}
          Resources:
            Slots: {{this.resource.slots}}
        {{/each}}
    1:
      Slot:
        CPU: {{slotsConfig.gpu.slot.cpu}}
        Memory: {{slotsConfig.gpu.slot.memory}}
      DefaultClass: {{slotsConfig.gpu.defaultClass}}
      Classes:
        {{#each slotsConfig.gpu.classes}}
        {{this.id}}:
          Name: {{this.name}}
          Description: {{this.description}}
          Order: {{this.order}}
          Resources:
            Slots: {{this.resource.slots}}
        {{/each}}
DedicatedMachines:
  InstanceTypes:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - t3.nano
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
    - t3.xlarge
    - t3.2xlarge
    - t3a.nano
    - t3a.micro
    - t3a.small
    - t3a.medium
    - t3a.large
    - t3a.xlarge
    - t3a.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - m4.16xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5.8xlarge
    - m5.12xlarge
    - m5.16xlarge
    - m5.24xlarge
    - m5a.large
    - m5a.xlarge
    - m5a.2xlarge
    - m5a.4xlarge
    - m5a.8xlarge
    - m5a.12xlarge
    - m5a.16xlarge
    - m5a.24xlarge
    - m5n.large
    - m5n.xlarge
    - m5n.2xlarge
    - m5n.4xlarge
    - m5n.8xlarge
    - m5n.12xlarge
    - m5n.16xlarge
    - m5n.24xlarge
    - m5zn.large
    - m5zn.xlarge
    - m5zn.2xlarge
    - m5zn.3xlarge
    - m5zn.6xlarge
    - m5zn.12xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - c5.large
    - c5.xlarge
    - c5.2xlarge
    - c5.4xlarge
    - c5.9xlarge
    - c5.12xlarge
    - c5.18xlarge
    - c5.24xlarge
    - c5a.large
    - c5a.xlarge
    - c5a.2xlarge
    - c5a.4xlarge
    - c5a.8xlarge
    - c5a.12xlarge
    - c5a.18xlarge
    - c5a.24xlarge
    - c5n.large
    - c5n.xlarge
    - c5n.2xlarge
    - c5n.4xlarge
    - c5n.9xlarge
    - c5n.18xlarge
    - r4.large
    - r4.xlarge
    - r4.2xlarge
    - r4.4xlarge
    - r4.8xlarge
    - r4.16xlarge
    - r5.large
    - r5.xlarge
    - r5.2xlarge
    - r5.4xlarge
    - r5.8xlarge
    - r5.12xlarge
    - r5.16xlarge
    - r5.24xlarge
    - r5a.large
    - r5a.xlarge
    - r5a.2xlarge
    - r5a.4xlarge
    - r5a.8xlarge
    - r5a.12xlarge
    - r5a.16xlarge
    - r5a.24xlarge
    - r5b.large
    - r5b.xlarge
    - r5b.2xlarge
    - r5b.4xlarge
    - r5b.8xlarge
    - r5b.12xlarge
    - r5b.16xlarge
    - r5b.24xlarge
    - r5n.large
    - r5n.xlarge
    - r5n.2xlarge
    - r5n.4xlarge
    - r5n.8xlarge
    - r5n.12xlarge
    - r5n.16xlarge
    - r5n.24xlarge
    - x1.16xlarge
    - x1.32xlarge
    - x1e.xlarge
    - x1e.2xlarge
    - x1e.4xlarge
    - x1e.8xlarge
    - x1e.16xlarge
    - x1e.32xlarge
    - p2.xlarge
    - p2.8xlarge
    - p2.16xlarge
    - p3.2xlarge
    - p3.8xlarge
    - p3.16xlarge
    - p3dn.24xlarge
    - p4d.24xlarge
    - g3s.xlarge
    - g3.4xlarge
    - g3.8xlarge
    - g3.16xlarge
  RecommendedInstanceTypes:
    - r5.8xlarge
    - r5.16xlarge
    - r5.24xlarge
    - p3.2xlarge
    - p3.8xlarge
    - p3.16xlarge
Features:
  DisableAnalytics: false
  {{#unless config.features.enableIntercom}}
  DisableIntercom: true
  {{/unless}}
  DirectPublication: true
  BasicMetadataOnly: true
  {{#if config.features.onboarding}}
  Onboarding: {{config.features.onboarding}}
  {{/if}}
  SlotScheduling: true
  DedicatedMachines: true
  {{#if config.features.useRInstallPackages}}
  UseRInstallPackages: true
  {{/if}}
  EnterprisePermissions: true
  Datasets: true
  RunOnlyCapsules: true
  {{#if config.features.disablePackageSuggestions}}
  DisablePackageSuggestions: true
  {{/if}}
  AlwaysGitIgnoreData: true
  CapsuleCredentials: true
  VPCDocumentation: true
  VPCAdministration: true
  ShowExamples: true
  DisableLicences: true
  MathworksAccounts: true
  PersistentCW: true
Datasets:
  CacheTTLDays: 30
Input:
  InputPath: /my-input
Services:
  affiliation:
    URL: http://afil:8091
  algorithm:
    URL: http://algo:8082
  analytic:
    URL: http://analytics:8093
  article:
    URL: http://arti:8104
  auth:
    URL: http://auth:8108
  collaboration:
    URL: http://cola:8094
  computation:
    URL: http://comp:8088
  credmap:
    URL: http://cred:8117
  cw-proxy:
    URL: http://cw-proxy:8114
  dataset:
    URL: http://dset:8099
  dataset-files:
    URL: http://dataset-files:8505
  dimage:
    URL: http://dimage:8113
  domain:
    URL: http://domain:8115
  image:
    URL: http://dock:8090
  field:
    URL: http://field:8084
  file:
    URL: http://file:8501
  file-internal:
    URL: http://file-internal:8501
  extension:
    URL: http://ext:8110
  git-proxy:
    URL: http://git-proxy:3050
  group:
    URL: http://group:8112
  gw:
    LocalBind: :8880
    URL: http://gw:8080
  ide:
    URL: http://ide:8109
  input-files:
    URL: http://input-files:8506
  installer:
    URL: http://inst:8102
  job:
    URL: http://job:8105
  journal:
    URL: http://jrnl:8098
  language:
    URL: http://lang:8083
  layout:
    URL: http://layout:8118
  machine:
    URL: http://mach:8116
  maintenance:
    URL: http://maint:8300
  notification:
    URL: http://noti:8101
  organization:
    URL: http://org:8111
  papi:
    URL: http://papi:8070
  payment:
    URL: http://pay:8100
  publisher:
    URL: http://pub:8103
  pubsim:
    URL: http://pubsim:8071
  rational:
    URL: http://rational:8600
  registry:
    URL: http://registry:5000
  result:
    URL: http://result:8503
  runconfig:
    URL: http://runcfg:8092
  rungui:
    URL: http://runi:8095
  starring:
    URL: http://star:8085
  status:
    URL: http://stat:8106
  swot:
    URL: http://swot:9900
  system:
    URL: http://system:8119
  token:
    URL: http://token:8107
  user:
    URL: http://users:8081
  viewing:
    URL: http://view:8086
  worker:
    URL: http://worker:8200
  workspace:
    URL: http://workspace:8500
