#!/usr/bin/env bash
set -ex

plot_title="Hello Code Ocean"
number_of_cycles=3
input_data="../data/sample-data.txt"

# Workaround for discrepancy in loaded packages between interactive and non-interactive execution
# See https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16921 for more details
export R_DEFAULT_PACKAGES=datasets,utils,grDevices,graphics,stats,methods

Rscript main.R "$plot_title" $number_of_cycles $input_data
