#!/usr/bin/env bash
set -ex

# Workaround for discrepancy in loaded packages between interactive and non-interactive execution
# See https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16921 for more details
export R_DEFAULT_PACKAGES=datasets,utils,grDevices,graphics,stats,methods

Rscript main.R "$@"
